server:
  port: 8083

#spring:
#  datasource:
#    url: jdbc:h2:mem:orderdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#  eureka:
#    client:
#      enabled: true
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
#    instance:
#      preferIpAddress: true
